---
kind: "Template"
apiVersion: "v1"
metadata: 
  name: "openshift-ansible"
  annotations:
    description: >
      Template for a build configuration and image streams to create a
      containerized image of openshift-ansible using OpenShift
    tags: "openshift-ansible"
  labels:
    template: openshift-ansible
objects: 
  - 
    kind: "BuildConfig"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}"
      annotations: 
        description: "Defines how to build the image"
    spec: 
      triggers: 
        - 
          type: "GitHub"
          github: 
            secret: "${GITHUB_WEBHOOK_SECRET}"
        - 
          type: "Generic"
          generic: 
            secret: "${GENERIC_WEBHOOK_SECRET}"
        - 
          type: "ConfigChange"
        - 
          type: "ImageChange"
      source: 
        type: "Git"
        git: 
          uri: "${SOURCE_REPO_URL}"
          ref: "${SOURCE_REPO_REF}"
        contextDir: "${SOURCE_CONTEXT}"
      strategy: 
        type: "Source"
        sourceStrategy: 
          from: 
            kind: "ImageStreamTag"
            name: "${BASE_IMAGESTREAM}:latest"
      output: 
        to: 
          kind: "ImageStreamTag"
          name: "${NAME}:latest"
  - 
    kind: "ImageStream"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}"
      annotations: 
        description: "Tracks the built image"
  - 
    kind: "ImageStream"
    apiVersion: "v1"
    metadata: 
      name: "${BASE_IMAGESTREAM}"
      annotations: 
        description: "Base image used to build ${NAME}"
    spec: 
      tags: 
        - 
          name: "latest"
          from: 
            kind: "DockerImage"
            name: "${BASE_IMAGE}"
parameters: 
  - 
    name: "NAME"
    displayName: "Name"
    description: "The name of the generated build config and image stream."
    required: true
    value: "openshift-ansible"
  - 
    name: "BASE_IMAGE"
    displayName: "Base image"
    description: "Base image to use for the source build."
    required: true
    value: "docker.io/aweiteka/playbook2image"
  - 
    name: "BASE_IMAGESTREAM"
    displayName: "Base imageStream"
    description: "Image stream to track the base image for the build."
    required: true
    value: "playbook2image"
  - 
    name: "SOURCE_REPO_URL"
    displayName: "Git Repository URL"
    description: "The URL of the repository with your application source code."
    required: true
    value: "https://github.com/openshift/openshift-ansible.git"
  - 
    name: "SOURCE_REPO_REF"
    displayName: "Git Reference"
    description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."
  - 
    name: "SOURCE_CONTEXT"
    displayName: "Context Directory"
    description: "Set this to the relative path to your project if it is not in the root of your repository."
  - 
    name: "GITHUB_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
  - 
    name: "GENERIC_WEBHOOK_SECRET"
    displayName: "Generic Webhook Secret"
    description: "A secret string used to configure the Generic webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
