# An example Dockerfile to package playbooks as docker image
# If using OpenShift, consider using the platform source2image build instead
FROM docker.io/aweiteka/playbook2image:latest

# OPTIONAL:
#ADD your_dynamic_inventory_script.py requirements.txt ${APP_HOME}
#RUN pip install -r ${APP_HOME}/requirements.txt

# uncomment if your playbook needs the oc CLI
#ENV INSTALL_OC=true

ADD YOUR_PLAYBOOK ${APP_HOME}

# Containers from the built image should invoke the default "run" script
# provided by the base image
CMD ["/usr/libexec/s2i/run"]
